AWSTemplateFormatVersion: 2010-09-09
Description: ---
Parameters: 
  ProjectName:
    Description: Project Name for CodeBuild
    Default: gs-build
    Type: String
  CodeCommitRepositoryName:
    Description: Source Repository Name
    Default: gs-vcs-repo
    Type: String
  ManagedPolicyName1:
    Description: Managed Policy 1
    Default: ECRManagementPolicy-gs-vcs-repo
    Type: String

Resources: 
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodeBuildRole-${ProjectName}
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
                - sts:AssumeRole
      Policies:
        - PolicyName: !Sub CodeBuildPolicy-${ProjectName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
      ManagedPolicyArns:
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/${ManagedPolicyName1}

  gsProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      BadgeEnabled: true
      Source:
        Type: CODECOMMIT
        Location: !Sub https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${CodeCommitRepositoryName}
      SourceVersion: refs/heads/main
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
      ServiceRole: !Ref CodeBuildServiceRole
      TimeoutInMinutes: 10
      QueuedTimeoutInMinutes: 10
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig:
        CloudWatchLogs:
          GroupName: gs-build-log-group
          Status: ENABLED
          StreamName: gs-build-log-stream
      Tags:
        - Key: Name
          Value: !Ref ProjectName
