AWSTemplateFormatVersion: 2010-09-09
Description: IAM Policies for ECR
Parameters: 
  CodeCommitRepositoryName:
    Description: Source Repository Name
    Default: gs-vcs-repo
    Type: String

Resources: 
  ECRManagementPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub ECRManagementPolicy-${CodeCommitRepositoryName}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ListImagesInRepository
            Effect: Allow
            Action: 
              - "ecr:ListImages"
            Resource:
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${CodeCommitRepositoryName}"
          - Sid: ManageRepositoryContents
            Effect: Allow
            Action: 
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetRepositoryPolicy"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:BatchGetImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"
            Resource:
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${CodeCommitRepositoryName}"
