AWSTemplateFormatVersion: 2010-09-09
Description: IAM Policies for ECR
Parameters: 
  ECRRepositoryName:
    Description: ECR Repository Name
    Default: gs-hello
    Type: String
  ECRBaseRepositoryName:
    Description: ECR Repository Name
    Default: gs-base
    Type: String

Resources: 
  ECRManagementPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub ECRManagementPolicy-${ECRRepositoryName}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ListImagesInRepository
            Effect: Allow
            Action: 
              - "ecr:ListImages"
            Resource:
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepositoryName}"
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRBaseRepositoryName}"
          - Sid: ManageRepositoryContents
            Effect: Allow
            Action: 
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetRepositoryPolicy"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:BatchGetImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"
            Resource:
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepositoryName}"
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRBaseRepositoryName}"
          - Sid: GetAuthorizationToken
            Effect: Allow
            Action:
              - "ecr:GetAuthorizationToken"
            Resource: "*"

